name: Node.js WhatsApp Bot CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v3

    - name: 🟢 Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: 📦 Install dependencies
      run: npm install

    - name: 🧪 Run tests
      run: npm test

    - name: 🧹 Lint (optional)
      run: npm run lint

    - name: 🔍 Check WhatsApp session (optional)
      run: |
        if [ -d "./session" ]; then
          echo "✅ Session folder exists"
        else
          echo "⚠️ Session folder missing"
        fi

    - name: 🚀 Deploy to server via SSH
      if: github.ref == 'refs/heads/main'
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_KEY }}
        port: 22
        script: |
          cd ~/whatsapp-bot
          git pull origin main
          npm install
          pm2 restart bot || pm2 start index.js --name bot
